FROM src
WORKDIR /go/src/github.com/openshift-hyperfleet/hyperfleet-infra
USER root
RUN yum -y install --setopt=skip_missing_names_on_install=False \
  shellcheck \
  jq \
  unzip \
  && yum clean all
RUN curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 \
  && chmod +x /tmp/get_helm.sh && /tmp/get_helm.sh && rm /tmp/get_helm.sh
RUN TERRAFORM_VERSION=1.9.8 \
  && curl -fsSL -o /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" \
  && unzip -o /tmp/terraform.zip -d /usr/local/bin/ && rm /tmp/terraform.zip
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
  && chmod 755 kubectl && mv kubectl /usr/local/bin/
RUN helm plugin install https://github.com/aslafy-z/helm-git
