apiVersion: v2
name: sentinel-clusters
description: Sentinel deployment for cluster lifecycle events
type: application
version: 0.1.0
appVersion: "0.0.0-dev"

dependencies:
  - name: hyperfleet-sentinel
    version: "1.0.0"
    repository: "git+https://github.com/openshift-hyperfleet/hyperfleet-sentinel@charts?ref=main"
